# On commit to master, pull updates in a repo that uses this repo as a submodule
name: push-submodule-update
on:
  # On push to master branch
  push:
    branches:
      - master
      - main
    # Only update if changes match one of these paths
    paths:
      - "/aoc/2021/**"
      - README.md
      - README.txt
      - LICENSE
      - .gitignore
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: emilyhunt/advent-of-code-21
          submodules: recursive
          token: ${{ secrets.write_pat }}
      - run: |
          git config user.name submodule-update-bot
          git config user.email "<>"
          git submodule update --remote
          git commit -am "Update submodules"
          git push